// Package dsp is offline, zero-phase signal conditioning for Go:
// IIR filter design, filtering as (b, a) or second-order sections,
// and frequency response, matching SciPy
//
// # Compatibility
//
// Every function matches its scipy.signal counterpart within a measured tolerance,
// checked against reference vectors generated by a pinned SciPy release:
//
//	Function       SciPy equivalent                 Worst measured   Tested to
//	Butter         butter (b, a)                    7.4e-15          1e-13
//	Butter + SOS   butter(output='sos')             7.3e-15          1e-13
//	ZPK.SOS        zpk2sos                          1.1e-16          1e-14
//	Filter         lfilter                          5.3e-16          1e-14
//	FilterState    lfilter with zi                  2.3e-16          1e-14
//	FilterZi       lfilter_zi                       1.7e-16          1e-14
//	FiltFilt       filtfilt                         7.7e-16          1e-14
//	SOSFilter      sosfilt, with and without zi     4.1e-14          1e-12
//	SOSFilterZi    sosfilt_zi                       9.8e-17          1e-14
//	SOSFiltFilt    sosfiltfilt                      1.7e-13          1e-11
//	Freqz          freqz                            1.2e-15          1e-13
//	SOSFreqz       freqz_sos                        3.7e-13          1e-11
//
// Errors are relative to the largest expected value, or for filtering to the
// largest input value if that's larger. For scale, 1e-16 is about one unit in
// the last place of a float64. The larger SOS figures all come from one
// deliberately difficult filter (order 8, cutoff 0.01), whose poles sit so close
// to z = 1 that single rounding differences between Go and SciPy are amplified;
// every other filter agrees within a few units in the last place.
//
// Where MATLAB's behaviour differs from SciPy's, SciPy's is the default and
// MATLAB's is an option, e.g. MATLABPadLen for filtfilt's padding length.
//
// # Filter representations
//
// Design functions return a ZPK: the filter's zeros, poles and gain. Its BA
// method gives transfer-function coefficients (b, a), for Filter and FiltFilt;
// its SOS method gives second-order sections, for SOSFilter and SOSFiltFilt.
// (b, a) is simple and matches MATLAB's most common usage, but loses precision
// as the order rises or the band narrows; second-order sections stay accurate,
// and are the better choice above order 4 or so.
//
// # Frequencies
//
// Band edges and cutoffs are normalised to Nyquist, as in SciPy and MATLAB:
// 0 < wn < 1, where 1 is half the sample rate. For a frequency f in Hz at sample
// rate fs, use f / (fs/2). Freqz and SOSFreqz return frequencies in rad/sample,
// also as SciPy and MATLAB do: divide by pi for Nyquist-normalised.
//
// # Conventions
//
// Every function is offline and stateless: the whole signal goes in as a
// slice, and a new slice comes back. Inputs are never modified, and nothing
// is shared between calls, so all functions are safe for concurrent use.
// To filter in blocks, FilterState and SOSFilterState take a starting state
// and return the final one, to pass to the next block.
//
// Invalid input returns an error wrapping one of the Err sentinels, so check
// for specific failures with errors.Is. Filtering functions don't check that a
// filter is stable; like SciPy and MATLAB, they assume it is.
package dsp
