// Package dsp is offline, zero-phase signal conditioning for GO:
// IIR filter design and forward-backward filtering, matching SciPy
//
// # Compatibility
//
// Every function matches its scipy.signal counterpart within a measured tolerance
// checked against reference vectors generated by a pinned SciPy release:
//
//	Function   SciPy equivalent        Worst measured   Tested to
//	Butter     scipy.signal.butter     7.4e-15          1e-13
//	Filter     scipy.signal.lfilter    5.3e-16          1e-14
//	FiltFilt   scipy.signal.filtfilt   7.7e-16          1e-14
//
// Errors are relative to the largest expected value, or for filtering to the
// largest input value if that's larger.
// For scale, 1e-16 is ~ 1 unit in the last place of float64, so a rounding error
//
// Where MATLAB's behaviour differs from SciPy's, SciPy's is the default and
// MATLAB's is an option, e.g. MATLABPadLen for filtfilt's padding length.
//
// # Frequencies
//
// Frequencies are normalised to Nyquist, as in SciPy and MATLAB: 0 < wn < 1,
// where 1 is half the sample rate.
// For a frequency f in Hz at sample rate fs, use f / (fs/2).
//
// # Conventions
//
// Every function is offline and stateless: the whole signal goes in as a
// slice, and a new slie comes back.
// Inputs are never modified, and nothing is shared between calls, so all
// functions are safe for concurrent use.
//
// Invalid input returns an error wrapping one of the Err sentinels, so check
// for specific failures with errors.Is .
// Filter and FiltFilt don't check that a filter is stable;
// like SciPy and MATLAB, they assume it is stable.
package dsp
